baseURL = "https://mulezamwiimbu.com/"
languageCode = "en"
title = "Muleza Mwiimbu & Company"
theme = "hugo-initio"

[params]
    name = "Muleza Mwiimbu & Company"
    description = "Advocates and Commissioners for Oaths"
    email = "mulezamwiimbu@gmail.com"
    phone = "+260 211 295968"
    address = "Plot No. 3796, Off Kwacha Road, Ngwerema Close, Olympia Park, Lusaka, Zambia"
    year = 2022
    avatar = "images/Scale.png"
    avatarclass = "circle"
    background = ""
    banner = "images/7sec.gif"
    favicon = "images/Scale favicon.png"
    DateForm = "January 2, 2006"
    author = "@WebAttire - The Trendiest Graphics"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Our Team"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fab fa-facebook-square"
    footer = false
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fab fa-twitter-square"
    footer = false
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fab fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fab fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fab fa-linkedin"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fab fa-github"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:mulezamwiimbu@gmail.com"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"
